% Write Matlab programs for the generation of elementary continuous time signals and discrete time signals.

figure(1);
theta=0:0.01:2*pi;
fun=sin(theta);
plot(theta,fun);
xlabel('\theta');
ylabel('sin(\theta)');
title('Plot of continous sin function');
figure(2);
theta=0:0.5:2*pi;
fun=sin(theta);
stem(theta,fun);
xlabel('\theta');
ylabel('sin(\theta)');
title('Plot of discrete sin function');
figure(3);
t=-1:0.01:2;
unitstep=(t>=0);
plot(t,unitstep);
xlabel('t');
ylabel('U(t)');
title('Plot of continous unit step function');
figure(4);
t=-1:0.5:2;
unitstep=(t>=0);
stem(t,unitstep);
xlabel('t');
ylabel('U(t)');
title('Plot of discrete unit step function');
figure(5);
t=-1:0.01:1;
myramp=t.*(t>=0)+0*(t<0);
plot(t,myramp,'b');
xlabel('t');
ylabel('Ramp(t)');
title('Plot of continous ramp function');
figure(6);
t=-1:0.2:1;
myramp=t.*(t>=0)+0*(t<0);
stem(t,myramp,'b');
xlabel('t');
ylabel('Ramp(t)');
title('Plot of discrete ramp function');
figure(7);
t=-5:0.01:5;
1
plot(t,exp(t));
xlabel('t');
ylabel('exp(t)');
title('Plot of continous exponential function');
figure(8);
t=-5:0.5:5;
stem(t,exp(t));
xlabel('t');
ylabel('exp(t)');
title('Plot of discrete exponential function');
figure(9);
t=-10:0.01:10;
plot(t,sinc(t));
xlabel('t');
ylabel('Sinc(t)');
title('Plot of continous sinc function');
figure(10);
t=-10:0.5:10;
stem(t,sinc(t));
xlabel('t');
ylabel('Sinc(t)');
title('Plot of discrete sinc function');
figure(11);
t=-1:0.01:2;
rect=1*(t>=0) -1*(t>1) ;
plot(t-0.5,rect,'b');
xlabel('t');
ylabel('Rect(t)');
title('Plot of continous Rectangular function');
figure(12);
t=-1:0.5:2;
rect=1*(t>=0) -1*(t>1) ;
stem(t-0.5,rect,'b');
xlabel('t');
ylabel('Rect(t)');
title('Plot of discrete Rectangular function');
